title: Victor Barbosa Martins
name: Victor Barbosa Martins
description: "Astroparticle Physicist | Professor at UFG"
url: "https://victorbarbosamartins.github.io"
baseurl: ""
repository: VictorBarbosaMartins/victorbarbosamartins.github.io

author:
  name: "Victor Barbosa Martins"
  avatar: "avatar.png"
  bio: "Astroparticle physicist focusing on very-high-energy gamma rays, cosmic rays, and multi-messenger astronomy."
  location: "Goiânia, Brazil"
  email: "barbosamartins@ufg.br"
  uri: "https://victorbarbosamartins.github.io"
  github: "VictorBarbosaMartins"
  linkedin: "victor-barbosa-martins"
  orcid: "0000-0002-5085-8828"
  google_scholar: "v_v_v_v_v_v_v"
  lattes: "0386103996676475"

include:
  - _pages

markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
