title: Victor Barbosa Martins
    2 name: Victor Barbosa Martins
    3 description: "Astroparticle Physicist | Professor at UFG"
    4 url: "https://victorbarbosamartins.github.io"
    5 baseurl: ""
    6 repository: VictorBarbosaMartins/victorbarbosamartins.github.io
    7
    8 author:
    9   name: "Victor Barbosa Martins"
   10   avatar: "avatar.png"
   11   bio: "Astroparticle physicist focusing on very-high-energy gamma rays, cosmic rays, and multi-messenger astronomy."
   12   location: "Goiânia, Brazil"
   13   email: "barbosamartins@ufg.br"
   14   uri: "https://victorbarbosamartins.github.io"
   15   github: "VictorBarbosaMartins"
   16   linkedin: "victor-barbosa-martins"
   17   orcid: "0000-0002-5085-8828"
   18   google_scholar: "v_v_v_v_v_v_v"
   19   lattes: "0386103996676475"
   20   researchgate: "Victor-Martins-4"
   21
   22 include:
   23   - _pages
   24
   25 markdown: kramdown
   26 theme: jekyll-theme-minimal
   27 plugins:
   28   - jekyll-feed
   29   - jekyll-gist
   30   - jekyll-paginate
   31   - jekyll-sitemap
