title: Victor Barbosa Martins
name: Victor Barbosa Martins
description: "Physical Engineer & Astroparticle Physicist | Professor at UFG"
url: "https://victorbarbosamartins.github.io"
baseurl: ""
repository: VictorBarbosaMartins/victorbarbosamartins.github.io

author:
  name: "Victor Barbosa Martins"
  avatar: "profile.jpg"
  bio: "Physical Engineer and Astroparticle physicist focusing on very-high-energy gamma rays and multi-messenger astronomy. Associated member of H.E.S.S. and member of LST - CTAO (via RUB)."
  location: "Goiânia, Brazil"
  email: "barbosamartins@ufg.br"
  uri: "https://victorbarbosamartins.github.io"
  github: "VictorBarbosaMartins"
  linkedin: "victor-barbosa-martins"
  orcid: "https://orcid.org/0000-0002-5085-8828"
  googlescholar: "https://scholar.google.com/citations?user=Dgp_1fkAAAAJ&hl=en"
  lattes: "http://lattes.cnpq.br/0386103996676475"

collections:
  publications:
    output: true
    permalink: /publications/:path/
  teaching:
    output: true
    permalink: /teaching/:path/
  group:
    output: true
    permalink: /group/:path/

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/VictorBarbosaMartins"

include:
  - _pages

markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
